# Generated by Django 6.0.1 on 2026-01-24 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DamageReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reported_by", models.CharField(max_length=100)),
                ("damage_type", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=200)),
                ("severity_level", models.CharField(max_length=20)),
                ("description", models.TextField()),
                ("report_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
