# Generated by Django 6.0.1 on 2026-01-24 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="damagereport",
            old_name="damage_type",
            new_name="district",
        ),
        migrations.RenameField(
            model_name="damagereport",
            old_name="severity_level",
            new_name="urgency",
        ),
        migrations.RemoveField(
            model_name="damagereport",
            name="location",
        ),
        migrations.AddField(
            model_name="damagereport",
            name="infrastructure_type",
            field=models.CharField(default="Route", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="damagereport",
            name="municipality",
            field=models.CharField(
                default="Kathmandu Metropolitan City", max_length=150
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="damagereport",
            name="skills_required",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="damagereport",
            name="volunteers_registered",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="damagereport",
            name="volunteers_required",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="damagereport",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="damagereport",
            name="reported_by",
            field=models.CharField(default="Anonymous", max_length=100),
        ),
    ]
