# Generated by Django 6.0.1 on 2026-01-24 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_rename_damage_type_damagereport_district_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="damagereport",
            old_name="report_date",
            new_name="created_at",
        ),
        migrations.RemoveField(
            model_name="damagereport",
            name="description",
        ),
        migrations.RemoveField(
            model_name="damagereport",
            name="district",
        ),
        migrations.RemoveField(
            model_name="damagereport",
            name="municipality",
        ),
        migrations.RemoveField(
            model_name="damagereport",
            name="reported_by",
        ),
        migrations.RemoveField(
            model_name="damagereport",
            name="urgency",
        ),
        migrations.RemoveField(
            model_name="damagereport",
            name="volunteers_registered",
        ),
        migrations.RemoveField(
            model_name="damagereport",
            name="volunteers_required",
        ),
        migrations.AddField(
            model_name="damagereport",
            name="category",
            field=models.CharField(default="Other", max_length=50),
        ),
        migrations.AddField(
            model_name="damagereport",
            name="damage_desc",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="damagereport",
            name="damage_name",
            field=models.CharField(default="Unknown", max_length=200),
        ),
        migrations.AddField(
            model_name="damagereport",
            name="damage_type",
            field=models.TextField(blank=True, default="[]"),
        ),
        migrations.AddField(
            model_name="damagereport",
            name="duration",
            field=models.CharField(default="2 hours", max_length=50),
        ),
        migrations.AddField(
            model_name="damagereport",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="damage_reports/"),
        ),
        migrations.AddField(
            model_name="damagereport",
            name="latitude",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="damagereport",
            name="longitude",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="damagereport",
            name="number_of_volunteer",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="damagereport",
            name="reporting_location",
            field=models.CharField(blank=True, default="", max_length=300),
        ),
        migrations.AddField(
            model_name="damagereport",
            name="urgency_level",
            field=models.CharField(default="Low", max_length=20),
        ),
        migrations.AlterField(
            model_name="damagereport",
            name="infrastructure_type",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="damagereport",
            name="skills_required",
            field=models.TextField(blank=True, default="[]"),
        ),
    ]
